<?php

namespace AppBundle\Repository;

/**
 * AbusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbusesRepository extends \Doctrine\ORM\EntityRepository
{
}
