<?php

namespace AppBundle\Repository;

/**
 * AbuseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbuseRepository extends \Doctrine\ORM\EntityRepository
{
}
