<?php

namespace AppBundle\Repository;

/**
 * BlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocksRepository extends \Doctrine\ORM\EntityRepository
{
}
