<?php

namespace AppBundle\Repository;

/**
 * CitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
