<?php

namespace AppBundle\Repository;

/**
 * FavoritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritesRepository extends \Doctrine\ORM\EntityRepository
{
}
