<?php

namespace AppBundle\Repository;

/**
 * LocalitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
