<?php

namespace AppBundle\Repository;

/**
 * NewslettersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslettersRepository extends \Doctrine\ORM\EntityRepository
{
}
