<?php

namespace AppBundle\Repository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends \Doctrine\ORM\EntityRepository
{
}
