<?php

namespace AppBundle\Repository;

/**
 * PostcodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcodesRepository extends \Doctrine\ORM\EntityRepository
{
}
