<?php

namespace AppBundle\Repository;

/**
 * PostalCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCodesRepository extends \Doctrine\ORM\EntityRepository
{
}
