<?php

namespace AppBundle\Repository;

/**
 * PostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
