<?php

namespace AppBundle\Repository;

/**
 * PromotionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionsRepository extends \Doctrine\ORM\EntityRepository
{
}
