<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
        public function MyFindAll(){
            $qb=$this->createQueryBuilder('p')
                ->leftJoin('p.images','i')
                ->leftJoin('p.provider','pr')
                ->leftJoin('p.serviceCategory','s')
                ->addSelect('i','pr','s');
            return $qb->getQuery()->getResult();

        }
}
