<?php

namespace AppBundle\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProviders($id) {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->leftJoin('p.categorie', 'cat')
            ->addSelect('cat');
        $query = $this->addJoins($qb);
        return $query->getQuery()->getSingleResult();
    }
}
