<?php

namespace AppBundle\Repository;

/**
 * ProvidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvidersRepository extends \Doctrine\ORM\EntityRepository
{
}
