<?php

namespace AppBundle\Repository;

/**
 * SendMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendMailRepository extends \Doctrine\ORM\EntityRepository
{
}
