<?php

namespace AppBundle\Repository;

/**
 * ServiceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneJointCourses($id){
        $qb=$this->createQueryBuilder('sc')
            ->where('sc.id=:id')
            ->setParameter(':id',$id)
            ->leftJoin('sc.providers','p')
            ->addSelect('p');
        $query=$this->addJoin($qb);
        return $query->getQuery()->getSingleResult();

    }
    public function myFindAll(){
        $qb=$this->createQueryBuilder('sc')
            ->leftJoin('sc.providers','p')
            ->addSelect('p');
        $query=$this->addJoin($qb);
        return $query->getQuery()->getResult();
    }
    public function findWithName($name){
        $qb=$this->createQueryBuilder('sc');
           $qb ->where($qb->expr()->like('sc.name', $qb->expr()->literal('%' . $name . '%')))
               ->leftJoin('sc.providers','p')
               ->addSelect('p');
           $query=$this->addJoin($qb);
           return $query->getQuery()->getResult();
    }
    public function findWithProvider($provider){
        $qb=$this->createQueryBuilder('sc');
        $qb->join('sc.providers', 'p', 'WITH', 'p = :provider')
            ->setParameter('provider',$provider);
        $query=$this->addJoin($qb);
        return $query->getQuery()->getResult();
    }
    public function findWithNameProvider($name,$provider){
        $qb=$this->createQueryBuilder('sc');
        $qb->where($qb->expr()->like('sc.name',$qb->expr()->literal('%'.$name.'%')))
            ->leftJoin('sc.providers','p','WITH','p = :provider')
            ->setParameter('provider',$provider);
        $query=$this->addJoin($qb);
        return $query->getQuery()->getResult();
    }
    public function addJoin(\Doctrine\ORM\QueryBuilder $qb){
        $qb->leftJoin('sc.promotions','pm')
            ->leftJoin('sc.courses','c')
            ->addSelect('pm','c');
        return $qb;

    }
}
