<?php

namespace AppBundle\Repository;

/**
 * ServiceCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
