<?php

namespace AppBundle\Repository;

/**
 * VisitorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorsRepository extends \Doctrine\ORM\EntityRepository
{
}
